[2018-02-06T18:10:23.038Z]  INFO: app/22630 on andriss-MacBook-Pro-2.local: New comment by top_kek_top
    comment: {
      "subreddit_id": "t5_2s3qj",
      "approved_at_utc": null,
      "edited": false,
      "mod_reason_by": null,
      "banned_by": null,
      "removal_reason": null,
      "link_id": "t3_7vngqy",
      "link_author": "Speaking-of-segues",
      "likes": null,
      "replies": [],
      "user_reports": [],
      "saved": false,
      "id": "dttzq1x",
      "banned_at_utc": null,
      "mod_reason_title": null,
      "gilded": 0,
      "archived": false,
      "report_reasons": null,
      "author": "top_kek_top",
      "num_comments": 45,
      "can_mod_post": false,
      "parent_id": "t1_dttpzjl",
      "score": 1,
      "approved_by": null,
      "over_18": false,
      "mod_note": null,
      "collapsed": false,
      "body": "In this one guys messed up head that's what happens, he hoards all the bitcoins buying them all at .0001, eventually making them worthless to everyone except him. ",
      "link_title": "'Dr Doom' Roubini says bitcoin 'nuts' will hold the cryptocurrency until it crashes to zero",
      "author_flair_css_class": null,
      "downs": 0,
      "is_submitter": false,
      "collapsed_reason": null,
      "body_html": "<div class=\"md\"><p>In this one guys messed up head that&#39;s what happens, he hoards all the bitcoins buying them all at .0001, eventually making them worthless to everyone except him. </p>\n</div>",
      "distinguished": null,
      "quarantine": false,
      "can_gild": true,
      "subreddit": "Bitcoin",
      "name": "t1_dttzq1x",
      "score_hidden": true,
      "permalink": "/r/Bitcoin/comments/7vngqy/dr_doom_roubini_says_bitcoin_nuts_will_hold_the/dttzq1x/",
      "num_reports": null,
      "link_permalink": "https://www.reddit.com/r/Bitcoin/comments/7vngqy/dr_doom_roubini_says_bitcoin_nuts_will_hold_the/",
      "stickied": false,
      "created": 1517969420,
      "author_flair_text": null,
      "link_url": "https://www.cnbc.com/2018/02/06/bitcoin-price-will-crash-to-zero-nouriel-roubini-says.html",
      "created_utc": 1517940620,
      "subreddit_name_prefixed": "r/Bitcoin",
      "controversiality": 0,
      "mod_reports": [],
      "subreddit_type": "public",
      "ups": 1
    }
